language: cpp
jobs:
  include:
    - name: Windows + VS2019
      os: windows
      install:
        - choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
        - choco install doxygen.install
    - name: Linux + GCC
      os: linux
      dist: focal
      install:
        - sudo apt-get update
        - sudo apt-get install cmake doxygen
    - name: Linux + Clang
      os: linux
      dist: focal
      env:
        - CC=clang
        - CXX=clang++
      install:
        - sudo apt-get update
        - sudo apt-get install cmake doxygen

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - cmake --build . --config Debug
  - ctest -V
  - cmake --build . --config Debug --target cesium-native-docs
